### ISSUE TITLE
Confirm/upload volunteer agreement

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/Strawberry-Fields-2018#2]
Kim is waiting confirmation from tara about wording of the Volunteer Agreement, to give us more legal power to pursue failed charges.

@jarvisjohnson please see if there is anything you;'d like to change :)

Can this please be viewable from the volunteer portal and as a pop up which needs to be agreed to when volunteers accept their position?

We'll also need to figure out the best way to display the Terms and Conditions, or whether we should amalgamate them into one document??

[STRAWBERRY FIELDS Volunteer Agreement.docx](https://github.com/volunteer-manage/Strawberry-Fields-2018/files/2172461/STRAWBERRY.FIELDS.Volunteer.Agreement.docx)

**Comment by KimPong** [comment]
@jarvisjohnson Ihave re-sent the agreement to Tara so hopefully we will have approval soon!

**Comment by KimPong** [comment]
@jarvisjohnson 
Please see final approved agreement to be displayed in the portal and which vols must tick to agree to in order to confirm their position.

[STRAWBERRY FIELDS Volunteer Agreement.docx](https://github.com/volunteer-manage/Strawberry-Fields-2018/files/2215923/STRAWBERRY.FIELDS.Volunteer.Agreement.docx)

**Comment by jarvisjohnson** [comment]
@KimPong 

This is uploaded, and visible [here](https://strawberry-fields.shyftly.com/pages/volunteer_terms)

You can edit it [here](https://strawberry-fields.shyftly.com/admin/settings) at the the bottom of the page

**Comment by KimPong** [comment]
@jarvisjohnson thanks for uploading, the second link takes me to the app page - can't see anywhere to edit anything?

**Comment by jarvisjohnson** [comment]
@KimPong 

So that link should take you to the admin section, the settings page - at the bottom of it you would be 
able to see the terms / edit them.

If you weren't logged in for some reason when you clicked that link, it wouldn't have taken you to the admin

You asked in the other issue about the terms and whether I had written them myself... 

The Strawberry Fields terms are those [here](https://strawberry-fields.shyftly.com/pages/volunteer_terms) - those are the ones you can edit.    They are linked to in the application form.

Are you asking about the terms of use of the website in the footer?  Yes, that is something I wrote, so not related to Strawberry.

**Comment by KimPong** [comment]
thanks @jarvisjohnson 
I was talking about this page, which it links to as well as the Volunteer agreement under the credit card details: https://shyftly.com/pages/volunteer_terms

**Comment by jarvisjohnson** [comment]
Oh ok gotcha @KimPong.  Yeah that is just generic terms if an event signed up and did not have their own terms written.

I will remove that link from the form so their is only the specific Strawberry terms page linked to.

**Comment by KimPong** [comment]
@jarvisjohnson ok thanks. pretty good idea to have generic terms, they seem pretty thorough. i just wasnt sure if they were written by competitor website or something x
