### ISSUE TITLE
Final issues/changes before launch

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/Strawberry-Fields-2018#5]
@jarvisjohnson Could you please have a look at these things? x

Most important to least important:

- Hitting 'Submit Application' but nothing is happening., so  cannot complete the application.  No error message is displayed.

- Allow 16/11/18 to be selected for earliest arrival date.

LANDING PAGE - less critical
- am unable to click on the 'Apply to volunteer' buttons below the three separate jobs, so is it possible to remove them from view? Or make the buttons active? whichever is easier.
- I update the event description in the admin section, and click Update Event. But the changes do not save.
I can edit some things, like the application deadline, but not others, like the decline shifts deadline. 
Have attempted multiple times.

**Comment by KimPong** [comment]
Trying to reset password and received this error: 
![screen shot 2018-07-30 at 12 38 58 pm](https://user-images.githubusercontent.com/29219132/43375073-407b1858-93f6-11e8-8184-bc8aef54aee7.png)

**Comment by jarvisjohnson** [comment]
@KimPong 

I have fixed these things.

Application not submitting was a Stripe problem, have sorted it,

The dates to arrive and leave - you can change them in the settings in the admin (they were the dates you gave me... ) But they are updated now anyway.

The admin settings section works now.

Resetting password works for me, I think the problem is you are trying to put in a password that is too short...
